# Generated by Django 4.2.5 on 2023-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(verbose_name='Продолжительность'),
        ),
    ]
