# Generated by Django 4.2.5 on 2023-09-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.CharField(default=str, max_length=250, verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
