# Generated by Django 4.2.5 on 2023-09-26 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_lesson_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProductAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.product')),
            ],
        ),
    ]
